### ISSUE TITLE
Errores al instalar

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/p31_mod#1]
Al instalar por primera vez y en todas las páginas de administración.
No es bloqueante.
Observado en versión 4.3.4

parent does not exist!
line 948 of /lib/adminlib.php: call to debugging()
line 113 of /mod/certifygen/classes/plugininfo/certifygenvalidation.php: call to admin_category->add()
line 96 of /mod/certifygen/settings.php: call to mod_certifygen\plugininfo\certifygenvalidation->load_settings()
line 158 of /lib/classes/plugininfo/mod.php: call to include()
line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
line 8783 of /lib/adminlib.php: call to require()
line 8664 of /lib/adminlib.php: call to admin_get_root()
line 19 of /admin/upgradesettings.php: call to admin_externalpage_setup()

**Comment by juacas** [comment]
En settings.php, las categorias de adminsettings siguientes no existen pero se usan de "parent":
"certifygenreportplugins"
"certifygenvalidationplugins"

**Comment by xpazv** [comment]
En revisión.

**Comment by xpazv** [comment]
Reproducido en 4.3 y 4.1

**Comment by xpazv** [comment]
Detalle completo
`parent does not exist!
line 948 of /lib/adminlib.php: call to debugging()
line 113 of /mod/certifygen/classes/plugininfo/certifygenvalidation.php: call to admin_category->add()
line 96 of /mod/certifygen/settings.php: call to mod_certifygen\plugininfo\certifygenvalidation->load_settings()
line 158 of /lib/classes/plugininfo/mod.php: call to include()
line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
line 8783 of /lib/adminlib.php: call to require()
line 8664 of /lib/adminlib.php: call to admin_get_root()
line 28 of /admin/search.php: call to admin_externalpage_setup()
parent does not exist!
line 948 of /lib/adminlib.php: call to debugging()
line 113 of /mod/certifygen/classes/plugininfo/certifygenvalidation.php: call to admin_category->add()
line 96 of /mod/certifygen/settings.php: call to mod_certifygen\plugininfo\certifygenvalidation->load_settings()
line 158 of /lib/classes/plugininfo/mod.php: call to include()
line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
line 8783 of /lib/adminlib.php: call to require()
line 8664 of /lib/adminlib.php: call to admin_get_root()
line 28 of /admin/search.php: call to admin_externalpage_setup()
parent does not exist!
line 948 of /lib/adminlib.php: call to debugging()
line 116 of /mod/certifygen/classes/plugininfo/certifygenreport.php: call to admin_category->add()
line 101 of /mod/certifygen/settings.php: call to mod_certifygen\plugininfo\certifygenreport->load_settings()
line 158 of /lib/classes/plugininfo/mod.php: call to include()
line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
line 8783 of /lib/adminlib.php: call to require()
line 8664 of /lib/adminlib.php: call to admin_get_root()
line 28 of /admin/search.php: call to admin_externalpage_setup()
parent does not exist!
line 948 of /lib/adminlib.php: call to debugging()
line 113 of /mod/certifygen/classes/plugininfo/certifygenvalidation.php: call to admin_category->add()
line 96 of /mod/certifygen/settings.php: call to mod_certifygen\plugininfo\certifygenvalidation->load_settings()
line 158 of /lib/classes/plugininfo/mod.php: call to include()
line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
line 8783 of /lib/adminlib.php: call to require()
line 31 of /admin/search.php: call to admin_get_root()
parent does not exist!
line 948 of /lib/adminlib.php: call to debugging()
line 113 of /mod/certifygen/classes/plugininfo/certifygenvalidation.php: call to admin_category->add()
line 96 of /mod/certifygen/settings.php: call to mod_certifygen\plugininfo\certifygenvalidation->load_settings()
line 158 of /lib/classes/plugininfo/mod.php: call to include()
line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
line 8783 of /lib/adminlib.php: call to require()
line 31 of /admin/search.php: call to admin_get_root()
parent does not exist!
line 948 of /lib/adminlib.php: call to debugging()
line 116 of /mod/certifygen/classes/plugininfo/certifygenreport.php: call to admin_category->add()
line 101 of /mod/certifygen/settings.php: call to mod_certifygen\plugininfo\certifygenreport->load_settings()
line 158 of /lib/classes/plugininfo/mod.php: call to include()
line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
line 8783 of /lib/adminlib.php: call to require()
line 31 of /admin/search.php: call to admin_get_root()`

**Comment by elena3ip** [comment]
En moodle4.1 también se observa. Se sube la corrección en la próxima subida a la rama develop
