### ISSUE TITLE
Al gestionar los modelos, hay cuatro get_string malformados

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/p31_mod#12]
Buenas,

En classes/forms/modelform.php, hay un par de referencias de *get_string* que apuntan a un módulo inexistente.
- ./classes/forms/modelform.php:101:        $templateoptions = ['' => get_string('chooseatemplate', 'coursecertificate')] + $templates;
- ./classes/forms/modelform.php:103:        $elements = [$mform->createElement('select', 'templateid', get_string('template', 'coursecertificate'), $templateoptions)];
- ./classes/forms/modelform.php:108:                $OUTPUT->action_link($manageurl, get_string('managetemplates', 'coursecertificate')));
- ./classes/forms/modelform.php:110:        $mform->addGroup($elements, 'template_group', get_string('template', 'coursecertificate'),

Un saludo

**Comment by elena3ip** [comment]
Ya esta la corrección subida en la rama develop
