### ISSUE TITLE
Error al previsualizar un template - Division by 0

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/p31_mod#13]
Buenas,

Al ir a previsualizar un template almacenado, nos está dando una división por 0.

URL: []/admin/tool/certificate/view.php?templateid=1&preview=1&code=previewing
Error stack:
```
Exception - Division by zero

[More information about this error](https://docs.moodle.org/401/en/error/moodle/generalexceptionmessage)
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 614 of /admin/tool/certificate/classes/element_helper.php: DivisionByZeroError thrown
    line 634 of /admin/tool/certificate/classes/element_helper.php: call to tool_certificate\element_helper::calculate_image_size()
    line 174 of /admin/tool/certificate/element/image/classes/element.php: call to tool_certificate\element_helper::render_image()
    line 290 of /admin/tool/certificate/classes/template.php: call to certificateelement_image\element->render()
    line 38 of /admin/tool/certificate/view.php: call to tool_certificate\template->generate_pdf()
```

Un saludo

**Comment by tmas0** [comment]
Buenas,

Este error solo pasa con el template generado de forma inicial al instalar el plugin. Cuando lo generamos de forma manual, la previsualización funciona bien.

Un saludo

**Comment by tmas0** [comment]
Buenas @xpazv,

Claro, sin problema: Hemos descargado el código, instalada, y en la pantalla de configuración hemos dado directamente a guardar, sin alternar nada de nada.

Un saludo

**Comment by xpazv** [comment]
En revisión, pues el error que se indica es de tool_certificate, no de mod_certifygen

**Comment by elena3ip** [comment]
@tmas0  qué plugin has instalado? el tool_certificate o el certificateelement_activity? yo en moodle 4.1 no reproduzco ese error.
¿qué version de tool_certificate estás usando?
