### ISSUE TITLE
Defecto de usabilidad en selección de contextos.

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/p31_mod#15]
A la hora de seleccionar los contextos a los que hay que asignar un modelo el interfaz de búsqueda no ayuda en absoluto por los siguientes motivos:

1. Hay que escribir tres letras para empezar a poder seleccionar. Esto obliga a consultar en otra pestaña el nombre de la categoría.
2. No se puede ver el contexto de las categorías elegidas. Por lo que no se puede elegir la categoría adecuada  (figura 1)
3. En realidad no se obtienen resultados hasta escribir 4 letras (figura 2).
4. El interfaz idóneo es el de la figura 6, del que tenemos una implementación muy competente en el proyecto UNIMOODLE https://github.com/UNIMOODLE/moodle-local_notificationsagent/blob/3ab90cebb4eac7daf918e174cc5bb8c885738156/amd/src/notification_assigntemplate.js#L18. (imita el funcionamiento combinado del nativo de Moodle en la figura 6).
5. Una opción más simple es la figura 4 que es como lo resuelve MoodleHQ en tool/certificate.
6. El interfaz actual no permite saber qué categorías son las seleccionadas pues el contexto jerárquico se ha perdido (figura 5).

En conclusión: el UX actual de la asignación de categorías y cursos es inutilizable. Solicitamos que se reutilice la implementación del plugin local_notificationsagent. 
Dado que esta función ocurre en una página de administrador (asignación a contextos) no es preocupante que tenga un rendimiento de carga pobre en sites, con una estructura muy compleja. La implementación carga toda la estructura de categorías recursivamente, pero en las instalaciones habituales tendremos cientos de categorías y unos pocos miles de cursos. Se ha probado el interfaz en el otro plugin y el funcionamiento es aceptable.

Figura 1:
![image](https://github.com/user-attachments/assets/11d485cb-8a36-439d-8a8c-fbc37dab14dd)
Figura 2:
![image](https://github.com/user-attachments/assets/5ad99161-6456-4038-983a-47fdfdd3e789)
Figura 3:
![image](https://github.com/user-attachments/assets/155fc646-f3ad-4b4b-89ba-f3cedfa287f7)
Figura 4:
![image](https://github.com/user-attachments/assets/7bb954fb-5d86-40e0-8364-d4930f8abbef)
Figura 5:
![image](https://github.com/user-attachments/assets/56d9ceeb-ca69-4b93-b0d6-f67c9c572c3b)
Figura 6:
![image](https://github.com/user-attachments/assets/8d51675c-a2bb-449a-9278-d3a7c4baa19a)

**Comment by juacas** [comment]
La implementación de Moodle de admin_settings_coursecat_select es como la figura 4 anterior y es el widget por defecto de Moodle para esta operación:
![image](https://github.com/user-attachments/assets/b7318cc1-10e9-42c8-b22b-5b81d1a38036)

**Comment by xpazv** [comment]
Respecto al mínimo de caracteres necesarios para que el interfaz muestre resultados, recomendamos encarecidamente establecer un mínimo de caracteres diferente de uno, pues en entornos con muchos cursos y/o categorias, puede penalizar el rendimiento en la búsqueda de cursos y categorias.

Por este motivo, se recomienda establecer un minimo de dos o tres caracteres.

**Comment by xpazv** [comment]
El interfaz de la figura 6, en un entorno de muchas categorias, decenas o cientos, puede penarlizar el rendimiento del interfaz.

Si el arbol de categorias tiene muchos niveles de profundidad, la experiencia de usuario se puede resentir, pues obliga a hacer scroll continuamente, así como colapsar o expandir categorias y subcategorias para navegar por el árbol y seleccionar categorias especificas en diferentes sitios del árbol.

**Comment by juacas** [comment]
Los puntos 1 y 3 se refieren a que el texto pide escribir 3 caracteres pero no hace la búsqueda hasta incluir el cuarto. Aunque es el menor de los problemas.

Lo mejor es una navegación desplegable similar a 3 o 6. En el peor de los casos como en 4.
Si no veis viable una implementación como la de 6 (está probada y aceptada en el P4), al menos que sea como admin_settings_coursecat_select 

He intentado usar la implementación actual (parcheando el bug #5) y es casi inutilizable principalmente por los motivos 1,2,3 y 6

**Comment by juacas** [comment]
Otro pequeño defecto del diálogo modal de selección: el desplegable de selección queda oculto por debajo del frame del diálogo:
![image](https://github.com/user-attachments/assets/cbbf47c8-5a5c-4902-933b-49feec455373)

Con una lista larga de elementos la navegación es antinatural ya que hay que desplazar el zoom de la ventana en lugar de solo desplazar el desplegable.

**Comment by xpazv** [comment]
Se acuerda implementar el buscador de manera que los candidatos sean mostrados con el contexto (_camino de migas con nombres cortos de las categorias, tanto para categorias o cursos_)

**Comment by xpazv** [comment]
Se debe valorar la precarga de los valores, porque en entornos de muchas categorias o cursos, puede tener impacto en el rendimiento de búsqueda o consulta.

**Comment by xpazv** [comment]
Se acuerda reducir la cantidad minima de caracteres, aunque es necesario indicar que puede dar lugar a problemas de rendimiento en la búsqueda, si el caracter es muy común (_vocales como a o e_)

**Comment by juacas** [comment]
Por si aporta algo: He probado un combo de admin_settings_coursecat_select con la estructura de categorías de producción de la UVa y el combo con todas las categorías cargadas (250) es super funcional y rápido.

**Comment by elena3ip** [comment]
Subido a develop el cambio

**Comment by jmerinogranizo** [comment]
Comprobado por mi parte. A la espera de que los demás den el visto bueno.

**Comment by juacas** [comment]
Permanece presente aún este defecto que impacta bastante en el interfaz.

> Otro pequeño defecto del diálogo modal de selección: el desplegable de selección queda oculto por debajo del frame del diálogo: ![image](https://private-user-images.githubusercontent.com/1656180/359390451-cbbf47c8-5a5c-4902-933b-49feec455373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNzk0NTgsIm5iZiI6MTcyNjA3OTE1OCwicGF0aCI6Ii8xNjU2MTgwLzM1OTM5MDQ1MS1jYmJmNDdjOC01YTVjLTQ5MDItOTMzYi00OWZlZWM0NTUzNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMTgyNTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmJiMTYzYTQxOWQ4MjA3NjBhYjRkYTIzMTljMWNkMDFlNWQ4NmI4ZDYyMGE5MTZiNzg0ZDczYmE3YmY0YzhkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uG_srKzrGFTyMPM3l91PY8XSvPpoOc10iPm2JeuKWnc)
> 
> Con una lista larga de elementos la navegación es antinatural ya que hay que desplazar el zoom de la ventana en lugar de solo desplazar el desplegable.
