### ISSUE TITLE
Generación del subplugin de postprocesamiento (tipo de generación) WSR

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/p31_mod#17]
Tal como se ha comentado en la reunión del día 21/08/24 y tal como se comentó en la reunión del día 14/06/24 y que cito ahora mismo:

_Se les explica a 3iPunt que la manera más sencilla que concebimos (unimoodle) el CERT-WSR, es que sea tratado además como un subplugin al igual que CMD y CSV en donde se asocie un modelo con ese subplugin de postproceso.

- El usuario profesor creará ese tipo de certificado asociado a ese modelo.

- El usuario desde el sistema externo sólo verá las actividades del tipo de subplugin WSR a las que tenga acceso por los criterios de visibilidad propios de la actividad.

- El usuario que acceda a la actividad desde el curso de Moodle, verá un aviso que indique al usuario que el estado del certificado está en fase “Pending” y que debe solicitarlo desde el sistema externo correspondiente._

necesitamos por tanto un nuevo subplugin de postprocesamiento (tipo de generación) "WSR".

En la reunión de hoy se ha determinado que se evaluará cómo implementarlo y la posibilidad de crear un nuevo servicio web que sea llamado por el sistema externo para actualizar el estado de la petición del usuario de "No iniciado o Pending" a "Generado".

Nota adicional: para el caso de los certificados de profesor, una opción que se me ocurre es que el profesor primero lo solicite vía Moodle (se crearía la solicitud con estado "Pending" y un mensaje indicando que debe solicitarlo en el sistema externo) y que desde el sistema externo, obtenga las solicitudes pendientes del profesor en ese sistema de Moodle. Necesidad de servicio web para cambio de estado de la petición.

Saludos.

**Comment by juacas** [comment]
@jmerinogranizo Para el caso del certificado del profesor no veo necesario hacer la solicitud desde Moodle.
Si los Webservices permiten obtener el listado de cursos del profesor y la solicitud de un certificado enumerando los cursos a certificar todo se puede hacer desde la "Administración electrónica". Creo que es más sensato implementarlo únicamente como un procedimiento de adm. electrónica.

**Comment by xpazv** [comment]
Tras valorarlo, se propone implementar un subplugin de tipo validación, denominado _"servicio externo"_ que disponibiliza un servicio web específico al que el sistema externo llama para cambiar el estado de la petición, de _pendiente_ a _validado_

**Comment by xpazv** [comment]
Se incluye en próxima version.
