### ISSUE TITLE
Creación de modelos. Modo de descarga repetivo

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/p31_mod#19]
En la reunión del día 18 de julio, se habló que el administrador, en la creación del modelo, podría establecer la frecuencia o intervalos en horas/días, etc mientras que actualmente está sólo en días.
No sé si redujo la funcionalidad en una reunión posterior.

**Comment by xpazv** [comment]
Está en proceso de implementación.

**Comment by elena3ip** [comment]
Ya esta subido a develop

**Comment by jmerinogranizo** [comment]
Comprobado por mi parte. No sé si los demás quieren establecer periodos en que se mezclen horas, minutos....
