### ISSUE TITLE
Creación de modelos. Subplugin de postprocesamiento o validación.

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/p31_mod#21]
¿En la creación de los modelos debería tener siempre asociado un subplugin de postprocesamiento o no y en ese caso no se hace nada ningún tratamiento del certificado? Lo digo por marcarlo como requerido.

**Comment by xpazv** [comment]
Tal y como está implementado ahora mismo, no es necesario indicar un plugin de postprocesamiento, en ninguno de los dos pasos (_validación y repositorio_)

**Comment by juacas** [comment]
De acuerdo siempre que la lógica esté 100% en subplugins (por ejemplo que no haya casos particulares implementados en el plugin principal)

**Comment by jmerinogranizo** [comment]
> De acuerdo siempre que la lógica esté 100% en subplugins (por ejemplo que no haya casos particulares implementados en el plugin principal), lo cual hace obligatorio el subplugin de almacenamiento.

Creo necesario que ese campo "generación o validación" sea requerido y que  exista un subplugin de validación ("Sin validación") que no haga nada realmente en vez de dejar la opción ("Seleccionar la validación del certificado") para que no haga ningún tipo de validación.

**Comment by elena3ip** [comment]
Hola, ya está subido a develop el plugin de validacion "none" y el de repositorio "local" de tal manera q ahora ambos elementos en el formulario son obligatorios

**Comment by jmerinogranizo** [comment]
Comprobado.
