### ISSUE TITLE
Descarga de certificados 

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/p31_mod#26]
En la vista /mod/certifygen/view.php?id=879 ni el profesor, administrador ni estudiante pueden ver o descargar los certificados que ya están validados.

![image](https://github.com/user-attachments/assets/48ceefcb-94dc-40a9-ab51-023536c13ff9)

En cambio en la página de tool_certificate ese mismo certificado se puede verificar y descargar:

![image](https://github.com/user-attachments/assets/67d9a22b-1aac-4a48-8c4e-df6078b12e99)

Versión: 2024081401

**Comment by xpazv** [comment]
El código da acceso al documento preliminar, sin validar ni almacenar.

**Comment by xpazv** [comment]
El proceso se concibe de manera completa, por lo que el documento no debe estar disponible hasta que el proceso de emision, con todos los pasos determinados por el modelo (_validacion, almacenamiento_) han sido completados.

**Comment by xpazv** [comment]
Valorar la eliminacion de la columna código, al menos para usuarios sin capability de administrar certifyGEN, para evitar posibles usos indebidos.

**Comment by juacas** [comment]
¿Saldrán de todas formas en "/admin/tool/certificate/my.php"?

**Comment by xpazv** [comment]
Si, en ese punto aparece porque es propio del **_tool_certificate_**
