### ISSUE TITLE
Actividad certificado del alumno. Selección de modelo sin validación asociada. bug 

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/p31_mod#28]
Se puede crear un modelo sin validación asociada y luego ser seleccionado por el profesor a la hora de crear la actividad.

**Comment by xpazv** [comment]
¿Nos puedes indicar @jmerinogranizo en qué sentido se considera este supuesto un bug?

¿Se debe controlar que los modelos de actividad tengan siempre seleccionado el subplugin de validación?

**Comment by juacas** [comment]
No veo contradicción lógica en que un modelo no tenga validación (o un plugin de validación que no haga nada, lo que es lo mismo pero con una arquitectura más elegante).

Este issue es duplicado del #21 .

Lo que sí es un problema es cómo gestionar que un tipo de plugin de almacenamiento no sea compatible con otros plugins de validación. Por ejemplo, el almacenamiento CSV solo puede funcionar en tándem con el validador CSV.
Sugiero que se añada un método en el api de subplugin de repositorio p.ej. get_requirements() que devuelva un array de plugins obligatorios, y al menos poder mostrar un error en el validador del formulario de creación de modelos.

**Comment by xpazv** [comment]
La depedencia entre subplugins, en el caso de CSV, es correcta, pero es necesario valorar adecuadamente la introducción de estas dependencias y excepciones específicas, porque pueden entrar en conflicto con la flexibilidad del enfoque mediante subplugins.

**Comment by xpazv** [comment]
El caso de los subplugins de CSV es muy específico, pero la incompatibilidad puede darse en todas las combinaciones.

Este es uno de los motivos por los que cada subplugin tiene la opcion de habilitarse o deshabilitarse, via configuración de la plataforma.

**Comment by juacas** [comment]
por eso propongo añadir un método para ello en el API.

¿Qué os parece un método "validate(model)" que deje en manos del subplugin determinar si la configuración del modelo es válida?

La implementación es bastante trivial y es suficiente con incluir la llamada en el método validate del formulario de modelos.

Es una forma de descargar en la implementación de los plugins esos detalles específicos.

**Comment by jmerinogranizo** [comment]
> Se puede crear un modelo sin validación asociada y luego ser seleccionado por el profesor a la hora de crear la actividad.

Si queréis, podemos cerrar el issue 21 pero creo que lo primero es que un modelo debe tener una validación asociada. Es decir, que ese campo "generación o validación" sea requerido y que exista un subplugin de validación ("Sin validación") que no haga nada realmente en vez de dejar la opción ("Seleccionar la validación del certificado") para que no haga ningún tipo de validación.

No me parece mal que exista ese método validate que además de requerir un tipo de validación asociada, controle esas dependencias.
