### ISSUE TITLE
Certificado en estado "pending" es validado por tool_certificate

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/p31_mod#29]
Cuando un certificado está en estado pending, ya tiene un certificateID con el que se puede verificar y descargar mediante toolcertificate.

Un certificado en estado pending no debe tener un certificateID válido o al menos éste no debe ser visible para los usuarios.

**Comment by xpazv** [comment]
El certificateID es el código de certificado que se muestra en el listado de peticiones

**Comment by xpazv** [comment]
Valoramos con @elena3ip retirar ese dato, para evitar vinculación con tool_certificate

**Comment by elena3ip** [comment]
Ya está eliminada la columna code de la tabla
