### ISSUE TITLE
Error de validación al crear instancia

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/p31_mod#3]
Al crear una instancia de mod_certifygen sin elegir un modelo, el formulario intenta crear la instancia dando el error:

Debug info: modelid: Required field
Error code: invalidpersistenterror×Dismiss this notification
Stack trace:
line 498 of /lib/classes/persistent.php: core\invalid_persistent_exception thrown
line 102 of /mod/certifygen/lib.php: call to core\persistent->create()
line 140 of /course/modlib.php: call to certifygen_add_instance()
line 185 of /course/modedit.php: call to add_moduleinfo()

El comportamiento esperado es una validación previa del formulario.

**Comment by xpazv** [comment]
Reproducido en 4.3

**Comment by elena3ip** [comment]
Reproducido en moodle 4.1. Lo corrijo.
