### ISSUE TITLE
El identificador de certificado sigue asociado al pdf original sin pasar por el validador.

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/p31_mod#30]
Secuencia:
- defina un modelo con una plantilla y validador CSV.
- lanza una request. Pasa a estado "pending".
- el certificateID sirve para descargar en tool_certificate el PDF generado por tool_certificate.
- ejecuta el cron. El certificado pasa a estado "Validado". Se supone que el PDF que se ha obtenido del servicio CSV está firmado y modificado.

Resultado no deseable:
- el certificateID sirve para descargar desde tool_certificate el PDF generado originalmente por tool_certificate.

Resultado esperado:
- el certificateID debería descargar el PDF modificado por el validador externo, o en caso de CSV redirigir a la URL de verificación que define el método CSV.

¿Es posible adaptar tool_certificate?
¿Cuál es el plan para sortear este problema?
¿Certifygen va a implementar un url de verificación análogo al de tool_certificate?

**Comment by xpazv** [comment]
Disculpa @juacas pero no entendemos los pasos 3 y 4 de la secuencia ¿A qué hace referencia el CertificateID?

**Tool_certificate** genera el PDF preliminar, pero este no se disponibiliza en plataforma, sino que es enviado al subplugin de CSV, para que este realizado su labor, procesando el fichero enviado y remitiendo la URL de descarga, para que la plataforma lo recopile, para posteriores pasos del proceso.

**Comment by xpazv** [comment]
Se elimina la representación del código de certificado via web
