### ISSUE TITLE
Certificado de profesor atascado en fase "Validated"

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/p31_mod#31]
Escenario:
- modelo de informe de profesor con validación CSV o CMD  y almacenamiento CSV o almacenamiento Local.
- Se solicita el informe.
- Se ejecuta cron varias veces.
- El certificado pasa a estado "Validated" y no evoluciona de ahí.
- No aparece el botón de descarga (porque no está "finished")

Versión del módulo: 2024081401

**Comment by xpazv** [comment]
Se añadirá logs de errores donde se pueda consultar el detalle del error en las peticiones.
