### ISSUE TITLE
Actividad certificado del alumno. Rol de profesor. Acceso a Gestión de Modelos. Visibilidad de enlaces "Editar, Borrar y Asignar contextos".

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/p31_mod#32]
Quería preguntar que aporta que el profesor pueda acceder a Gestión de Modelos desde la actividad de certificado de alumno si no se le ofrece más información que en la lista desplegable. Diferentes opciones:

1. No mostrarle ese enlace por que no le aporta nada adicional al profesor
2. A la hora de crear el modelo, establecer un campo descripción del modelo y mostrar ese campo cuando se acceda a Gestión de modelos.

Si el profesor u otro rol tiene esa posibilidad de acceder a "Gestión de modelos" desde la actividad, si no tiene capacidad de realizar las funciones de edición, borrado y asignación de contextos, no se debería mostrar los enlaces en vez de que te los muestren y luego al pinchar te dé un error de permisos.

**Comment by elena3ip** [comment]
pendiente de subida el control del enlace con capability

**Comment by elena3ip** [comment]
Ya está en develop el control por capability

**Comment by jmerinogranizo** [comment]
Funciona. ¿Qué capacidad es la que lo controla? ¿mod/certifygen:manage a nivel de sistema?

**Comment by jmerinogranizo** [comment]
Ya comentado en #22 .Se cierra.
