### ISSUE TITLE
Gestión de modelos. Posibilidad de edición una vez emitidos certificados.

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/p31_mod#33]
El usuario administrador o gestor de modelos puede realizar cambios en el modelo cuando ya hay certificados emitidos. Por ejemplo:

- Cambios en el idioma: si se cambia de idioma, los certificados emitidos siguen estando en ese idioma pero sólo se visualizarán los certificados emitidos en los idiomas actualmente disponibles. Si hay marcha atrás, se volverán a visualizar los certificados que se emitieron en su momento.
- Cambios en el tipo de generación/validación: se siguen viendo los certificados emitidos en otra validación al actual.
- Cambios en la plantilla: se ven los certificados pero sin campo de verificación o código ni la fecha de emisión.

No se debería permitir cambios en el modelo si hay certificados emitidos en alguna actividad de alumno o petición de certificado del profesor.

**Comment by juacas** [comment]
Yo prefiero que el modelo seleccionado no afecte al listado de certificados emitidos y que éstos se vean siempre ya que existen por sí mismos y cambiar el modelo no los invalidan si se emitieron en el pasado correctamente. Al igual que en #10 es preferible  que los listados sean más  generales e independientes de las variables del modelo, por ejemplo comenzar el listado sin filtrar por idioma y permitir en el filtro elegir todos los idiomas del site.

Creo que es más práctico permitir que el modelo pueda cambiarse. Preveo muchos casos de uso en los que haga falta cambiar el modelo en algún aspecto sin tener que repetir los certificados ya emitidos.

El modelo se puede cambiar por otro distinto, o también se pueden modificar los atributos uno a uno. En ambos casos se cambia el comportamiento del módulo en los certificados siguientes.
Si quisiéramos controlar eso (aparte de que creo que es contraproducente) implicaría comprobar:
- que no se cambie el modelo por otro (instancia distinta).
- que no se modifique algún atributo del modelo anterior. Dado que los modelos se reutilizan en todo el site esto implicaría mantener un histórico congelado del modelo. Lo veo problemático.


Este issue es igual que el #23

**Comment by xpazv** [comment]
Por nuestra parte, el código de bloqueo ya está realizado, pero en vista de lo expuesto, necesitamos que nos confirmeis si procedemos o mantenemos la lógica actual que no bloquea @juacas @jmerinogranizo

**Comment by xpazv** [comment]
Por nuestra parte, consideramos necesario el bloqueo, porque hay condiciones, como la validación o el repositorio, que si cambian, pueden dar lugar a incoherencias.

Si el modelo originalmente tiene modo repositorio local, y posteriormente se cambia a modo repositorio OneDrive, el sistema no sabrá como recuperar los ficheros generados en el otro modo, lo que dará lugar a incoherencias (_peticiones de certificado cursadas, con fichero generado, pero no accesible por cambio de algún parámetro del modelo_)

**Comment by juacas** [comment]
Me convence totalmente el argumento del subplugin de almacenamiento. 
Pero tengo dudas de cómo se maneja eso cuando es el administrador el que edita el modelo. ¿Se bloquea para el administrador también?

Si ya está hecho y diseñado teniendo todo esto en cuenta, estoy de acuerdo.

**Comment by elena3ip** [comment]
Hola, ya están las comprobaciones en la rama develop

**Comment by jmerinogranizo** [comment]
Comprobado.
