### ISSUE TITLE
Actividad certificado del alumno. El profesor puede solicitar la emisión de un certificado de un alumno.

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/p31_mod#35]
En una actividad de certificado del alumno, el profesor puede emitir un certificado por parte del alumno.

**Comment by juacas** [comment]
En la actividad course_certificate de Moodle el profesor puede revocar y regenerar el certificado.

![image](https://github.com/user-attachments/assets/602a59bd-2898-4b9f-8d9a-c19aa0c2e833)

Yo veo bien que exista esa posibilidad controlada con el capability (como este inexistente mod/certifygen:emitothers).

Tambien faltan capabilities como "mod/certifygen:revokeothers", "mod/certifygen:revokeown".

**Comment by jmerinogranizo** [comment]
> En la actividad course_certificate de Moodle el profesor puede revocar y regenerar el certificado.
> 
> ![image](https://private-user-images.githubusercontent.com/1656180/363176412-602a59bd-2898-4b9f-8d9a-c19aa0c2e833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzgwMjksIm5iZiI6MTcyNTI3NzcyOSwicGF0aCI6Ii8xNjU2MTgwLzM2MzE3NjQxMi02MDJhNTliZC0yODk4LTRiOWYtOGQ5YS1jMTlhYTBjMmU4MzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMTE0ODQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjE4MzBlMWViMTFiOTdmNDdlNDU2NDA0YjI5ZGZmZmZjNjk5ZTQ4ODlmYmIyMzkzOGYyMmM0ZTdhOTFhOGNlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O8TWTK5N1IK1D1HtECSmgJx7kC4gE7SuJbdd8jWCfg4)
> 
> Yo veo bien que exista esa posibilidad controlada con el capability (como este inexistente mod/certifygen:emitothers).
> 
> Tambien faltan capabilities como "mod/certifygen:revokeothers", "mod/certifygen:revokeown".

No lo recordaba. Entonces, me parece bien que esté esa funcionalidad y que se añadan esas capacidades.
