### ISSUE TITLE
Servicios web. No están accesibles las funciones del servicio web "Unimoodle CertifyGen".

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/p31_mod#36]
Cuando el administrador quiere ver los servicios web del plugin, aunque están habilitados al pinchar sobre las funciones de Unimoodle CertifyGen
![imagen](https://github.com/user-attachments/assets/21b23737-a60c-4b16-acfe-869ef517cf1d)

da el siguiente error:
![imagen](https://github.com/user-attachments/assets/43badc39-0303-479e-91d8-0be324b297ee)

¿Por cierto no deberían estar asociadas esas funciones a un usuario que tuviera un rol concreto? ¿Qué capacidades tendría ese rol? ¿Sería posible ofrecer al administrador la posibilidad de crear ese usuario, rol y token en un sólo clic como en el plugin de Unimoodle p32 (local_coursetransfer) que también habéis desarrollado vosotros?

**Comment by elena3ip** [comment]
Hola, a mi no me sale el error. Esa función, notify_certification ya no existe. Prueba a purgar caches y sino como acabo de subir código a la rama develop, en una instalación nueva del plugin no debería de salirte.

**Comment by jmerinogranizo** [comment]
Gracias Elena. He tenido que reinstalar pero ya me ha funcionado.
Estaría bien realizar la mejora que también he propuesto.

**Comment by xpazv** [comment]
Lo valoramos como mejora @jmerinogranizo porque algunas de las operaciones puede requerir que el usuario sea admin del sitio, y eso entraña riesgos _(nos hemos encontrado con esa problemática también en Course Transfer)_
