### ISSUE TITLE
Contexto erróneo en verificación de permisos: revokecertificate

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/p31_mod#37]
La comprobación de permiso se hace sobre el curso en lugar de sobre la actividad certifygen:

https://github.com/UNIMOODLE/p31_mod/blob/246fd2e732defd72c4b55990360a58878cad8df0/classes/external/revokecertificate_external.php#L99

Esto puede hacer que alguien con permisos retirados en la actividad ejecute las acciones, entre otros casos adversos.

Los permisos de acciones en un módulo deben checkearse con el contexto de módulo.

**Comment by elena3ip** [comment]
Esa parte es así por definición del tool_certificate, al ser otro plugin yo no puedo modificarle el contexto, es el que tiene definido.
