### ISSUE TITLE
External services: falta comprobación de capabilities y condiciones de disponibilidad

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/p31_mod#38]
En los servicios externos no se comprueban capabilities ni condiciones concretas de la operación a realizar (como si el cerficado es para el mismo usuario llamante o para terceros).

Por ejemplo:
https://github.com/UNIMOODLE/p31_mod/blob/246fd2e732defd72c4b55990360a58878cad8df0/classes/external/emitcertificate_external.php#L120

Actualmente cualquier usuario con sesión abierta puede emitir un certificado para otra persona usando una llamada al WS con sesskey y cookie válidas, aunque esta persona no cumpla las condiciones de disponibilidad del módulo.

Debe controlar con el contexto de instancia de módulo si se pide emitir certificado propio o no y si se poseen los capabilities mod/certifygen:emitothers o mod/certifygen:emitown en el contexto de módulo.

Lo mismo se aplica al resto de servicios externos.

relacionado con #35 #37

**Comment by jmerinogranizo** [comment]
Es más, como comentaba en #36, sería recomendable que el plugin tuviera la posibilidad de crear un rol específico y un usuario asociado a ese rol con las capacidades para ejecutar todos los servicios webs especificados. Ya hicisteis algo similar con el plugin que desarrollasteis de local_coursetransfer (lote 3.2).
Gracias.

**Comment by xpazv** [comment]
Se consigue reproducir en la versión actual, mediante peticion curl realizada con un usuario, cambiando el id de usuario

`  curl 'https://unimoodletest.3ip.eu/lib/ajax/service.php?sesskey=0Fx6dxPo9y&info=mod_certifygen_emitcertificate' \
  -H 'Accept: application/json, text/javascript, */*; q=0.01' \
  -H 'Accept-Language: es,pt;q=0.9,pt-BR;q=0.8,pt-PT;q=0.7,en;q=0.6,en-GB;q=0.5,en-US;q=0.4' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: _ga_WR7V0CR6MB=GS1.2.1699892165.3.0.1699892165.60.0.0; _ga_FWCB579M4Z=GS1.1.1717422621.2.0.1717422621.0.0.0; _ga=GA1.2.853365652.1595522176; _ga_E94G990M7R=GS1.1.1724056973.135.0.1724056976.0.0.0; MoodleSession=29qnvei85rp49pm593784fsspn; MOODLEID1_=%2585Tv%2581%25C1%2516%2595%25BE%250F%25BCI%257F%25A9F%25FB%255E%25BE%2505%25FF' \
  -H 'Origin: https://unimoodletest.3ip.eu' \
  -H 'Pragma: no-cache' \
  -H 'Referer: https://unimoodletest.3ip.eu/mod/certifygen/view.php?id=5425' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'sec-ch-ua: "Not;A=Brand";v="24", "Chromium";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --data-raw '[{"index":0,"methodname":"mod_certifygen_emitcertificate","args":{"id":0,"instanceid":1,"modelid":4,"lang":"es","userid":2028,"courseid":96}}]'`

**Comment by xpazv** [comment]
En revisión.

**Comment by juacas** [comment]
Las comprobaciones deben ser igual de exhaustivas que en los php clásicos: require_login, has_capabilities, contextos, campos userid de las tablas, etc.

**Comment by elena3ip** [comment]
Hola, ya están subidos los cambios a la rama develop

**Comment by jmerinogranizo** [comment]
Parece que está controlado por lo que yo he visto. Juan Pablo, tu puedes confírmalo con más seguridad.
