### ISSUE TITLE
Unificación tipo modelos de profesor

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/p31_mod#39]
Habiéndolo hablado en la reunión del 28/08/2024 se solicita unificar los dos tipos de certificado de profesor (del curso y de todos los cursos) a uno sólo para ser compatible a como ha evolucionado la funcionalidad de solicitud de certificado de profesor.

**Comment by xpazv** [comment]
Implementada. Pendiente de subida a develp

**Comment by elena3ip** [comment]
Hola, ya está subido el cambio a la rama develop

**Comment by jmerinogranizo** [comment]
Elena, elimina de los lang
$string['type_3'] = 'All courses used (for teachers)';
Cuando esté ya se puede cerrar la incidencia.

**Comment by elena3ip** [comment]
Preparado para la próxima subida a develop
