### ISSUE TITLE
Falla la búsqueda de categorías y cursos

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/p31_mod#4]
Al intentar asignar contexto a un modelo falla la búsqueda de categoría:
Error code: generalexceptionmessage
* line 42 of /mod/certifygen/classes/external/searchcategory_external.php: Error thrown
* line 147 of /lib/classes/component.php: call to include_once()
* line ? of unknownfile: call to core_component::classloader()
* line 62 of /lib/external/classes/external_api.php: call to class_exists()
* line 186 of /lib/external/classes/external_api.php: call to core_external\external_api::external_function_info()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

Error code: generalexceptionmessage
* line 42 of /mod/certifygen/classes/external/searchcategory_external.php: Error thrown
* line 147 of /lib/classes/component.php: call to include_once()
* line ? of unknownfile: call to core_component::classloader()
* line 62 of /lib/external/classes/external_api.php: call to class_exists()
* line 186 of /lib/external/classes/external_api.php: call to core_external\external_api::external_function_info()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

También falla la búsqueda de cursos:

Error code: generalexceptionmessage
* line 42 of /mod/certifygen/classes/external/searchcourse_external.php: Error thrown
* line 147 of /lib/classes/component.php: call to include_once()
* line ? of unknownfile: call to core_component::classloader()
* line 62 of /lib/external/classes/external_api.php: call to class_exists()
* line 186 of /lib/external/classes/external_api.php: call to core_external\external_api::external_function_info()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

Error code: generalexceptionmessage
* line 42 of /mod/certifygen/classes/external/searchcourse_external.php: Error thrown
* line 147 of /lib/classes/component.php: call to include_once()
* line ? of unknownfile: call to core_component::classloader()
* line 62 of /lib/external/classes/external_api.php: call to class_exists()
* line 186 of /lib/external/classes/external_api.php: call to core_external\external_api::external_function_info()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

Probado en 4.3.4

**Comment by xpazv** [comment]
Nos puedes indicar los siguientes datos:
- Modelo a asignar (estudiante, profesor)
- Contexto a asignar (curso, categoria)
- Versión de Moodle usada.

**Comment by elena3ip** [comment]
En un moodle 4.1 en mi local, no me da fallo con el debug activado

**Comment by juacas** [comment]
El gallo está provocado por el #5 
Arreglado el #5, se arreglará el #4
