### ISSUE TITLE
Asignación de contextos. Posibilidad de seleccionar todos los contextos.

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/p31_mod#40]
Como un modelo no puede estar asociado a ningún contexto, comentamos la posibilidad de que exista la posibilidad de que el usuario pueda elegir “todos los contextos” para que un modelo se aplique a todo el site. El modelo que esté asociado a “todos los contextos” estará asociado a los nuevos contextos que se creen en ese site.

**Comment by elena3ip** [comment]
Ya está en la rama develop

**Comment by jmerinogranizo** [comment]
Comprobado.

**Comment by jmerinogranizo** [comment]
Acabo de darme cuenta que si un modelo de tipo "alumno" está asociado a todos los contextos ("Sistema"), el profesor luego no puede seleccionar ese modelo para una actividad de certificación del alumno. 
Si el modelo es de tipo "profesor", el profesor si puede solicitar la creación de un certificado de profesor de ese modelo.

**Comment by elena3ip** [comment]
lo reviso ahora.gracias

**Comment by jmerinogranizo** [comment]
Además, el sw "mod_certifygen_get_courses_as_teacher" no coge los modelos asociados a Sistema por cada curso en los que está como profesor.

**Comment by elena3ip** [comment]
subido a develop la corrección de ambos errores.

**Comment by juacas** [comment]
No he sabido como asignar a todos los contextos. ¿El contexto "Sistema" equivale a "todos los contextos"?

**Comment by jmerinogranizo** [comment]
Yo entiendo que sí. Ahora haré pruebas.

**Comment by jmerinogranizo** [comment]
Comprobado.
