### ISSUE TITLE
Comprueba e informa de activación de protocolo SOAP

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/p31_mod#41]
En la configuración del Validations_CSV se puede habilitar el subplugin, pero no va a salir en ninguna parte si el Site tiene desactivado el protocolo SOAP.

A) ¿Es técnicamente necesario? En general esa activación de protocolo se refiere más a que los servicios "external" se publiquen con SOAP. Para los clientes no debería ser necesario.
B) En caso contrario, debe comprobarse esta configuración e informar que debe activarse el protocolo antes de activar el subplugin.

https://localhost/moodle40/admin/settings.php?section=webserviceprotocols

**Comment by xpazv** [comment]
En este caso, no lo consideramos necesario, porque el subplugin es cliente del servicio CSV.

La disponibiliización de servicios basados en SOAP en Moodle, para consumo externo, si requiere de un control y aviso.

**Comment by juacas** [comment]
Discrepo. Según https://docs.moodle.org/dev/Webservice_protocols estos plugins de tipo webservice protocol son solo para que sistemas EXTERNOS llamen a Moodle.
Es decir, controlan la instalación de SERVIDORES.

En el caso CSV no hay llamadas en sentido entrante. 

Después de analizar este tema un poco más a fondo, estoy convencido de que hay que eliminar esa comprobación de la línea 64 de csv_configuration.php.

De hecho nosotros no tenemos activado el servidor SOAP en explotación y debe ser posible conectar con otros servidores SOAP.
