### ISSUE TITLE
Creación de un modelo. Selección de varios idiomas no consecutivos

### ISSUE THREAD

**Issue by jmerinogranizo** [UNIMOODLE/p31_mod#48]
No consigo seleccionar varios idiomas no consecutivos cuando al menos hay tres idiomas para seleccionar.

**Comment by juacas** [comment]
¿Funciona pulsando la tecla Ctrl mientras haces click?

**Comment by jmerinogranizo** [comment]
Perdonad, pero deben haber sido las meigas por que yo juraría que estaba utilizando la famoso tecla de Ctrl.
Otra posibilidad (la más clara) es que esté hecho un zoquete y no le diera bien a esa tecla.
En fin...
