### ISSUE TITLE
Generación de los certificados con el último idioma de la lista

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/p31_mod#50]
Buenas,

Tenemos este caso de uso:
1. Sitio con 4 idiomas: es, en, eu, ca
2. Creamos un curso sin imposición de idioma.
3. Generamos la plantilla para que se pueda usar en 3 idiomas (ca, es, eu). (Aplicamos filtro mlang). ![Selecció_1323](https://github.com/user-attachments/assets/4d32336b-3465-490a-8b88-3f8e07d0a057)
4. Al ir a emitir un certificado, siempre se generan con el último idioma de la plantilla, imposibilitando la generación en un idioma en concreto.
![Selecció_1324](https://github.com/user-attachments/assets/94dcf449-8474-4519-a1c9-0e3c7e0b3eee)

Observamos si se aplica el filtro en concreto puedes llegar a manipular esa generación, pero no funciona en todos los casos.

Un saludo

**Comment by jmerinogranizo** [comment]
Toni, puede que esté relacionado con issues #9 y #10 .
¿Le pulsaste al botón Filter cuando seleccionaste el idioma? Si no le pulsaste al botón, sigue como seleccionado el que estuviera por defecto.

**Comment by tmas0** [comment]
Si, pero si no le das al botón y revisas la última imagen aportada, se ve que por defecto el filtro tiene Español **es**, pero la modal se levanta con Euskera **eu**. En todos los otros casos, funciona bien.

Un saludo

**Comment by jmerinogranizo** [comment]
> Si, pero si no le das al botón y revisas la última imagen aportada, se ve que por defecto el filtro tiene Español **es**, pero la modal se levanta con Euskera **eu**. En todos los otros casos, funciona bien.
> 
> Un saludo

Hola Toni, pero es lo que comento en el mensaje, que tienes que darle al botón Filter por que  a mí independientemente del idioma (ca en es) elegido si no le das a ese botón me sale siempre en catalán que es el que viene por defecto.
![imagen](https://github.com/user-attachments/assets/c1dde2e5-9b0c-4cf7-85fe-87d1683dcf5a)

![imagen](https://github.com/user-attachments/assets/29fcff71-89c0-48b9-af09-153d60fa4573)
Ya te digo que se solucionaría con lo comentado por Juan Pablo.

**Comment by tmas0** [comment]
Así es. Cierro a la espera de esas 2 incidencias. Se me habían colado.
