### ISSUE TITLE
Reubicación del enlace para el informe de actividad de un profesor (UX)

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/p31_mod#6]
En el perfil del usuario no aparece el enlace para acceder a los informes propios del profesor.
¿Lo estoy buscando en el sitio equivocado?

![image](https://github.com/user-attachments/assets/c76e84ed-7814-4d74-a79d-b9c77fe39275)

**Comment by xpazv** [comment]
Si no se tienen modelos de para profesor configurados y creados, no aparece el enlace en la ubicación mostrada en la imagen.

**Comment by juacas** [comment]
Comprobado.
Por usabilidad y coherencia con el diseño de tool_certificate, vamos a mover el enlace a la sección "Miscelaneous" justo al lado de "My certificates".
La posición actual rompe la lógica de la página del perfil.

**Comment by xpazv** [comment]
Se incluye en próxima versión.

**Comment by jmerinogranizo** [comment]
En la versión da7ffa64a5062dc2b36f7e5e8e391af2831f17ac de la rama develop creada el 28/08/24 sigue apareciendo en el mismo sitio y no en "Miscelánea".

**Comment by elena3ip** [comment]
Subido a develop. 
Perdonad que no se que ha pasado con este cambio... pensaba q lo tenía subido y en efecto no estaba.

**Comment by jmerinogranizo** [comment]
Reubicado correctamente. Relacionado con #34.
